### ISSUE TITLE
Another Interesting Stat

### ISSUE THREAD

**Issue by viceroypenguin** [jvanelteren/blog#13]
Really interesting stats!

One more stat that would be interesting in the first section: how many people have gotten all 350 stars thus far (all 50 stars in all 7 events so far).

**Comment by jvanelteren** [comment]
Thanks! It's interesting, but this information is not available on the AoC website... 
It is in Eric's database only :) The only user info we have is the stats page and the global leaderboard pages...

**Comment by viceroypenguin** [comment]
Oh - based on the level of detail, I assumed you were getting it from the database. I'm even more impressed with the amount of details you were able to extract just from the website. :)
